version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: illuminate/support
    versions:
    - 8.25.0
    - 8.26.1
    - 8.27.0
    - 8.28.1
    - 8.29.0
    - 8.30.0
    - 8.30.1
    - 8.31.0
    - 8.32.1
    - 8.33.1
    - 8.34.0
    - 8.35.1
    - 8.36.1
    - 8.36.2
    - 8.37.0
    - 8.38.0
  - dependency-name: php-di/php-di
    versions:
    - 6.3.1
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.3.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
    - 9.5.4
  - dependency-name: mockery/mockery
    versions:
    - 1.4.3
  - dependency-name: vlucas/phpdotenv
    versions:
    - 5.3.0
  - dependency-name: monolog/monolog
    versions:
    - 2.2.0
  - dependency-name: fzaninotto/faker
    versions:
    - 1.9.2
  - dependency-name: slim/slim
    versions:
    - 4.7.1
