version: '3.8'

services:
  application:
    container_name: jex.application
    image: othercode/jexupdate
    build: './docker'
    ports:
      - 9000:80
    volumes:
      - ../../:/opt/jexserver
      - ./usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ./usr/local/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /opt/jexserver

networks:
  default:
    name: jex.backnet
    driver: bridge

volumes:
  database:
    name: jex.database