name: Docker Image CI

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Build and tag Docker image
        run: docker build . --file Dockerfile \
          --tag othercode/jexupdate:${{steps.vars.outputs.tag}} \
          --tag othercode/jexupdate:latest

      - name: Push the tagged Docker image
        run: docker push othercode/jexupdate
